// import { VideoCardType, VideoDetailType } from '@/types/videoType';

// const videoItem: VideoDetailType = {
//  videoId: 1,
//  thumbnail: '/images/crying.jpg',
//  videoTitle: '현명하게 추석을 보내는 방법',
//  channelProfileUrl: '/images/crying.jpg',
//  channelName: '채널이름뭐로하지',
//  readCount: 100,
//  createAt: '2021-08-24',
//  content:
//    '추석을 현명하게 보내는 방법을 알려드립니다. 여러가지 방법이 있을겁니다. 아무래도 최고는 집밖에 안나가는거겠죠? 그럼 이만~',
//  videoUrl: 'https://www.youtube.com/embed/7C2z4GqqS5E',
//  recommendedList: [
//    {
//      videoId: 1,
//      thumbnail: '/images/crying.jpg',
//      videoTitle: '떼껄룩',
//      channelProfileUrl: '/images/crying.jpg',
//      channelName: '채널임다',
//      readCount: 100,
//      createAt: '2021-08-24',
//    },
//    {
//      videoId: 2,
//      thumbnail: '/images/crying.jpg',
//      videoTitle: '떼껄룩',
//      channelProfileUrl: '/images/crying.jpg',
//      channelName: '채널임다',
//      readCount: 100,
//      createAt: '2021-08-24',
//    },
//  ],
// };

// export const videoList: VideoCardType[] = [
//  {
//    videoId: 1,
//    thumbnail: '/images/crying_cat.jpg',
//    videoTitle: '아 재밌다',
//    channelProfileUrl: '/images/crying.jpg',
//    channelName: '피식대학',
//    readCount: 246,
//    createAt: '2023.06.23',
//  },
//  {
//    videoId: 2,
//    thumbnail: '/images/crying_cat.jpg',
//    videoTitle: '뭐하나',
//    channelProfileUrl: '/images/crying.jpg',
//    channelName: '피식대학',
//    readCount: 23,
//    createAt: '2023.06.23',
//  },
//  {
//    videoId: 3,
//    thumbnail: '/images/crying_cat.jpg',
//    videoTitle: '라면월드컵',
//    channelProfileUrl: '/images/crying.jpg',
//    channelName: '침착맨',
//    readCount: 45345,
//    createAt: '2023.06.23',
//  },
//  {
//    videoId: 4,
//    thumbnail: '/images/crying_cat.jpg',
//    videoTitle: '라면월드컵',
//    channelProfileUrl: '/images/crying.jpg',
//    channelName: '침착맨',
//    readCount: 45345,
//    createAt: '2023.06.23',
//  },
//  {
//    videoId: 5,
//    thumbnail: '/images/crying_cat.jpg',
//    videoTitle: '라면월드컵',
//    channelProfileUrl: '/images/crying.jpg',
//    channelName: '침착맨',
//    readCount: 45345,
//    createAt: '2023.06.23',
//  },
//  {
//    videoId: 6,
//    thumbnail: '/images/crying_cat.jpg',
//    videoTitle: '라면월드컵',
//    channelProfileUrl: '/images/crying.jpg',
//    channelName: '침착맨',
//    readCount: 45345,
//    createAt: '2023.06.23',
//  },
//  {
//    videoId: 7,
//    thumbnail: '/images/crying_cat.jpg',
//    videoTitle: '라면월드컵',
//    channelProfileUrl: '/images/crying.jpg',
//    channelName: '침착맨',
//    readCount: 45345,
//    createAt: '2023.06.23',
//  },
//  {
//    videoId: 8,
//    thumbnail: '/images/crying_cat.jpg',
//    videoTitle: '라면월드컵',
//    channelProfileUrl: '/images/crying.jpg',
//    channelName: '침착맨',
//    readCount: 45345,
//    createAt: '2023.06.23',
//  },
// ];

// export default videoItem;
